### ISSUE TITLE
Failing to run on my machine

### ISSUE THREAD

**Issue by szunami** [amethyst/space-menace#51]
Just checked out this project, currently at `9c697897875545461749ca8a1080d419e1f4427e`. 

Straight `cargo build` did not work, had to run off nightly; then I hit:

```
cargo +nightly run
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
     Running `target/debug/space-menace`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.12.0
[INFO][amethyst::app] Platform: x86_64-apple-darwin
[INFO][amethyst::app] Amethyst git commit: c72063f13f90bae4ae96b6c96e04a2206493bbf3
[INFO][amethyst::app] Rustc version: 1.44.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: b2e36e6c2d229126b59e892c9147fbb68115d292
thread 'main' panicked at 'attempted to leave type `std::mem::ManuallyDrop<error::BoxedErr>` uninitialized, which is invalid', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/libcore/mem/mod.rs:661:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: crossbeam::ms_queue::MsQueue<T>::new
  10: specs::common::Errors::new
  11: <specs::common::Errors as core::default::Default>::default
  12: amethyst::app::ApplicationBuilder<S,T,E,X>::new
  13: amethyst::app::CoreApplication<T,E,R>::build
  14: space_menace::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal
  17: std::rt::lang_start
  18: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-0.4.1/src/ms_queue.rs:204:20
stack backtrace:
   0:        0x10add87ff - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9b566daa2a455421
   1:        0x10adfcfce - core::fmt::write::ha1b9f49163694e4d
   2:        0x10add59f7 - std::io::Write::write_fmt::h5bf7ecb3d7765923
   3:        0x10adda8aa - std::panicking::default_hook::{{closure}}::h694d41cd08e58408
   4:        0x10adda5ec - std::panicking::default_hook::ha6f28bd33ba2e689
   5:        0x10addae78 - std::panicking::rust_panic_with_hook::hb00d3c1dea212869
   6:        0x10addaa42 - rust_begin_unwind
   7:        0x10ae2cf4f - core::panicking::panic_fmt::h1194552d43282424
   8:        0x10ae2cea7 - core::panicking::panic::h38c465954407f791
   9:        0x10ac9f035 - core::option::Option<T>::unwrap::haf563af5f22a5d9f
  10:        0x10acad0ce - crossbeam::ms_queue::MsQueue<T>::try_pop::h32dc8cb0851adbf2
  11:        0x10acaca5c - <crossbeam::ms_queue::MsQueue<T> as core::ops::drop::Drop>::drop::h7ab4bb3006e0ca51
  12:        0x10ac9b341 - core::ptr::drop_in_place::h69559e69411bed69
  13:        0x10acacf95 - crossbeam::ms_queue::MsQueue<T>::new::hd551644edc62a7bc
  14:        0x10acb1fd9 - specs::common::Errors::new::ha7b86883e631b1f1
  15:        0x10acb1fa4 - <specs::common::Errors as core::default::Default>::default::h63fbd81d1d7bedbe
  16:        0x109b2a1bf - amethyst::app::ApplicationBuilder<S,T,E,X>::new::h78d366a477c9cbd2
  17:        0x109b28d66 - amethyst::app::CoreApplication<T,E,R>::build::h00b2e48851f3d52b
  18:        0x1098219ce - space_menace::main::h00e17a6c79a477f3
  19:        0x10981f2ee - std::rt::lang_start::{{closure}}::hd7718dacc6536e7a
  20:        0x10addb2a9 - std::rt::lang_start_internal::hf66bdb55704675cb
  21:        0x10981f2d1 - std::rt::lang_start::h2dd39c1ac96bcb8f
  22:        0x109822152 - main
thread panicked while panicking. aborting.
[1]    40190 illegal hardware instruction  cargo +nightly run
```

```
cargo +nightly -V
cargo 1.44.0-nightly (8751eb301 2020-04-21)
```

**Comment by szunami** [comment]
Just tried running via  `cargo run --release`;

```
cargo run —release

    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/space-menace '—release'`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.12.0
[INFO][amethyst::app] Platform: x86_64-apple-darwin
[INFO][amethyst::app] Amethyst git commit: c72063f13f90bae4ae96b6c96e04a2206493bbf3
[INFO][amethyst::app] Rustc version: 1.44.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: b2e36e6c2d229126b59e892c9147fbb68115d292
thread 'main' panicked at 'attempted to leave type `std::mem::ManuallyDrop<error::BoxedErr>` uninitialized, which is invalid', /rustc/b2e36e6c2d229126b59e892c9147fbb68115d292/src/libcore/mem/mod.rs:661:5
stack backtrace:
[1]    40580 segmentation fault  cargo run —release
```

**Comment by szunami** [comment]
I was able to get this to work in https://github.com/amethyst/space-menace/pull/53

**Comment by krankur** [comment]
Closing this as the PR with the fix is merged. Thanks @szunami for taking care of this.
